package com.orion.model;

public enum GameEffect {
	THINK_INFLUENCE_TIMES, LABORER_INFLUENCE_TIMES, PATRON_INFLUENCE_TIMES, CRAFTSMAN_INFLUENCE_TIMES,
	THINK, DISCARD_ALL, MULTIPLE_ACTIONCARDS, DISCARD_ONE,
	DOUBLE_CLIENTS, CLIENTS_PLUS_TWO,  
	SAVE_ROLES,  DECK_TO_TREASURE,
	EXTRA_CLIENT, DOUBLE_CLIENT_ACTION, LABORER_EXTRA_CARD, USE_CLIENT,
	ARCHITECT_FROM_POOL, MERCHANT_FROM_HAND,
	MARBLE_JOKER, ALL_AS_STONE, BUILD_JOKER, RUBBLE_JOKER,	
	ALL_AS_ARCHITECT, ALL_AS_LABORER, MERCHANT_JOKER,
	GAME_ENDS, RESOURCES_GAME_WIN,	
	STEAL_CLIENTS, LEGIONARY_DEFENSE, BRIDGE_DEFENSE, STEAL_BUILDING, STEAL_TO_ALL, 
	MAKE_PUBLIC_BUILDING,
	THREE_EXTRA_POINTS, POINTS_BY_RESOURCE,
	FOUNTAIN, TABERN, VILLE,
	TREASURE_PLUS_TWO,
	MARBLE_UNCOMPLETED_EFFECTS, ONE_ACTION_OUTSKIRTS,
	MAX_HAND_PLUS_TWO, MAX_HAND_PLUS_FOUR,
	TAKE_SENATORS
	
}
