package com.orion.gar.model;

public enum GameTiming {
	
	PERMANENT, 
	BEFORE_THINK, 
	AFTER_THINK, AFTER_ACTION_CRAFTSMAN, AFTER_ACTION_PATRON,  
	ACTION_ARCHITECT, ACTION_MERCHANT, ACTION_LEGIONARY, ACTION_CRAFTSMAN, ACTION_LABORER, ACTION_PATRON,
	ON_COMPLETION, ON_TURN_END, ON_ACTION, ON_GAME_END, ON_CLIENT_ADD,
	TO_BUILD
}
